[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

; ---- credenciais do ramal SIP (preencha com os seus dados) ----
[nvoip_auth]
type=auth
auth_type=userpass
username=SEU_RAMAL_SIP
password=SUA_SENHA_SIP

[nvoip]
type=registration
transport=transport-udp
outbound_auth=nvoip_auth
server_uri=sip:sip.nvoip.com.br
client_uri=sip:SEU_RAMAL_SIP@sip.nvoip.com.br
contact_user=SEU_RAMAL_SIP
retry_interval=30
forbidden_retry_interval=60
expiration=300

[nvoip]
type=aor
contact=sip:sip.nvoip.com.br:5060
qualify_frequency=60

[nvoip]
type=endpoint
transport=transport-udp
context=from-nvoip
disallow=all
allow=ulaw,alaw
outbound_auth=nvoip_auth
aors=nvoip
from_user=SEU_RAMAL_SIP
from_domain=sip.nvoip.com.br
callerid=551152825287 <551152825287>
direct_media=no
; NAT: mantém o áudio no mesmo caminho por onde saímos
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[nvoip]
type=identify
endpoint=nvoip
match=sip.nvoip.com.br
